import type { MenuItemConfig, StaffRole } from "./types";

const ALL: StaffRole[] = [
  "admin",
  "ti",
  "marketing",
  "rh",
  "recepcao",
  "enfermagem",
  "administrativo",
];

export const DEFAULT_MENU: MenuItemConfig[] = [
  {
    key: "noticias",
    label: "Notícias",
    href: "/intranet/noticias",
    icon: "Newspaper",
    category: "Comunicação",
    order_num: 1,
    can_view: ALL,
    can_edit: ["admin", "ti", "marketing"],
    active: true,
  },
  {
    key: "eventos",
    label: "Eventos",
    href: "/intranet/eventos",
    icon: "Calendar",
    category: "Comunicação",
    order_num: 2,
    can_view: ALL,
    can_edit: ["admin", "ti", "marketing"],
    active: true,
  },
  {
    key: "corpo-clinico",
    label: "Corpo Clínico",
    href: "/intranet/corpo-clinico",
    icon: "Stethoscope",
    category: "Clínica",
    order_num: 3,
    can_view: ALL,
    can_edit: ["admin", "ti"],
    active: true,
  },
  {
    key: "ramais",
    label: "Ramais",
    href: "/intranet/ramais",
    icon: "Phone",
    category: "Clínica",
    order_num: 4,
    can_view: ALL,
    can_edit: ["admin", "ti"],
    active: true,
  },
  {
    key: "treinamentos",
    label: "Treinamentos",
    href: "/intranet/treinamentos",
    icon: "GraduationCap",
    category: "Capacitação",
    order_num: 5,
    can_view: ALL,
    can_edit: ["admin", "ti", "rh"],
    active: true,
  },
  {
    key: "documentos",
    label: "Documentos",
    href: "/intranet/documentos",
    icon: "FileText",
    category: "Capacitação",
    order_num: 6,
    can_view: ALL,
    can_edit: ["admin", "ti", "rh"],
    active: true,
  },
  {
    key: "assistente",
    label: "Assistente IA",
    href: "/intranet/assistente",
    icon: "Brain",
    category: "Suporte",
    order_num: 7,
    can_view: ALL,
    can_edit: ["admin", "ti"],
    active: true,
  },
  {
    key: "chamados",
    label: "Chamados TI",
    href: "/intranet/chamados",
    icon: "Ticket",
    category: "Suporte",
    order_num: 8,
    can_view: ALL,
    can_edit: ["admin", "ti"],
    active: true,
  },
  {
    key: "ponto",
    label: "Meu Ponto",
    href: "/intranet/ponto",
    icon: "Clock",
    category: "Ponto",
    order_num: 9,
    can_view: ALL,
    can_edit: ["admin", "ti", "rh"],
    active: true,
  },
  {
    key: "ponto-calendario",
    label: "Calendário Ponto",
    href: "/intranet/ponto/calendario",
    icon: "CalendarDays",
    category: "Ponto",
    order_num: 10,
    can_view: ALL,
    can_edit: ["admin", "ti", "rh"],
    active: true,
  },
];
