import type { MenuItemConfig, StaffRole } from "./types";

const ALL: StaffRole[] = [
  "admin",
  "ti",
  "marketing",
  "rh",
  "recepcao",
  "enfermagem",
  "administrativo",
  "manutencao",
];

export const DEFAULT_MENU: MenuItemConfig[] = [
  {
    key: "noticias",
    label: "Notícias",
    href: "/intranet/noticias",
    icon: "Newspaper",
    category: "Comunicação",
    order_num: 1,
    can_view: ALL,
    can_edit: ["admin", "ti", "marketing"],
    active: true,
  },
  {
    key: "eventos",
    label: "Eventos",
    href: "/intranet/eventos",
    icon: "Calendar",
    category: "Comunicação",
    order_num: 2,
    can_view: ALL,
    can_edit: ["admin", "ti", "marketing"],
    active: true,
  },
  {
    key: "ramais",
    label: "Ramais",
    href: "/intranet/ramais",
    icon: "Phone",
    category: "Comunicação",
    order_num: 3,
    can_view: ALL,
    can_edit: ["admin", "ti"],
    active: true,
  },
  {
    key: "corpo-clinico",
    label: "Corpo Clínico",
    href: "/intranet/corpo-clinico",
    icon: "Stethoscope",
    category: "Corpo Clínico e Procedimentos",
    order_num: 4,
    can_view: ALL,
    can_edit: ["admin", "ti", "marketing", "recepcao"],
    active: true,
  },
  {
    key: "procedimentos",
    label: "Procedimentos e Exames",
    href: "/intranet/procedimentos",
    icon: "ClipboardList",
    category: "Corpo Clínico e Procedimentos",
    order_num: 41,
    can_view: ALL,
    can_edit: ["admin", "ti", "marketing", "recepcao"],
    active: true,
  },
  {
    key: "treinamentos",
    label: "Treinamentos",
    href: "/intranet/treinamentos",
    icon: "GraduationCap",
    category: "Capacitação",
    order_num: 5,
    can_view: ALL,
    can_edit: ["admin", "ti", "rh"],
    active: true,
  },
  {
    key: "documentos",
    label: "Documentos",
    href: "/intranet/documentos",
    icon: "FileText",
    category: "Capacitação",
    order_num: 6,
    can_view: ALL,
    can_edit: ["admin", "ti", "rh"],
    active: true,
  },
  {
    key: "assistente",
    label: "Assistente IA",
    href: "/intranet/assistente",
    icon: "Brain",
    category: "Suporte",
    order_num: 7,
    can_view: ALL,
    can_edit: ["admin", "ti"],
    active: true,
  },
  {
    key: "chamados-ti",
    label: "Chamados TI",
    href: "/intranet/chamados/ti",
    icon: "Monitor",
    category: "Suporte",
    order_num: 8,
    can_view: ALL,
    can_edit: ["admin", "ti"],
    active: true,
  },
  {
    key: "chamados-manutencao",
    label: "Chamados Manutenção",
    href: "/intranet/chamados/manutencao",
    icon: "Wrench",
    category: "Suporte",
    order_num: 9,
    can_view: ALL,
    can_edit: ["admin", "manutencao"],
    active: true,
  },
  {
    key: "chamados-mkt",
    label: "Solicitações MKT",
    href: "/intranet/chamados/marketing",
    icon: "Megaphone",
    category: "Suporte",
    order_num: 10,
    can_view: ALL,
    can_edit: ["admin", "marketing"],
    active: true,
  },
  {
    key: "ponto",
    label: "Meu Ponto",
    href: "/intranet/ponto",
    icon: "Clock",
    category: "Ponto & RH",
    order_num: 9,
    can_view: ALL,
    can_edit: ["admin", "ti", "rh"],
    active: true,
  },
  {
    key: "ponto-calendario",
    label: "Calendário de Ponto",
    href: "/intranet/ponto/calendario",
    icon: "CalendarDays",
    category: "Ponto & RH",
    order_num: 10,
    can_view: ALL,
    can_edit: ["admin", "ti", "rh"],
    active: true,
  },
  {
    key: "ponto-aprovacoes",
    label: "Aprovação de Pontos",
    href: "/intranet/ponto/aprovacoes",
    icon: "CheckSquare",
    category: "Ponto & RH",
    order_num: 11,
    can_view: ["admin", "ti", "rh"],
    can_edit: ["admin", "ti", "rh"],
    active: true,
  },
];
